branches:
  only:
    - test
addons:
  apt:
    packages:
      - docker-ce
matrix:
  include:
    - language: java
      sudo: required
      jdk: oraclejdk8

      services:
        - docker

      before_install: cat ${env.MAVEN_REPO_NAME} && cp .travis.settings.xml $HOME/.m2/settings.xml && cat $HOME/.m2/settings.xml && cd $TRAVIS_BUILD_DIR/apiTemplate-base && mvn clean deploy && cd modules/apiTemplate-api

      install: true
      script:
        - |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            mvn install dockerfile:build
            mvn  dockerfile:push
            !