branches:
  only:
    - test
addons:
  apt:
    packages:
      - docker-ce
matrix:
  include:
    - language: java
      sudo: required
      jdk: oraclejdk8

      services:
        - docker

      before_install:
        - cp .travis.settings.xml $HOME/.m2/settings.xml
        - cd $TRAVIS_BUILD_DIR/apiTemplate-base
             #mvn clean deploy
        - cd modules/apiTemplate-api

      script:
        - |
            mvn clean install
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t kowkowal/test-api:api -f Dockerfile.fabric8 .
            docker push kowkowal/test-api:api
            #mvn install dockerfile:build
            #mvn  dockerfile:push
            !