template-db:
  container_name: template-db
  image: postgres:9.4
  volumes:
    - ~/postgres/data:/var/lib/postgresql/data
  ports:
    - 5432:5432
test-api:
  container_name: template-api
  image: DOCKER_HUB/DOCKER_IMAGE:tag
  ports:
    - 8080:8080
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - template-db:postgres
